# Flask settings
FLASK_SERVER_NAME = 'localhost'
FLASK_SERVER_PORT = 8008
FLASK_DEBUG = True

# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

# SQLAlchemy settings
SQLALCHEMY_DATABASE_URI = 'sqlite:///paster.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
